# Пользователи
@hostname = http://localhost
@port = 3000
@host = {{hostname}}:{{port}}
@prefix = api
@parentPath = posts
@contentType = application/json
@userId = 64568b7912955db48eb0f9d7
@token = ''


# Create a new post
POST {{host}}/{{prefix}}/{{parentPath}} HTTP/1.1
Content-Type: {{contentType}}

{
  "title": "Hello world! 22222",
  "description": "Текст анонса 2222",
  "content": "Расширенный текст публикации",
  "userId": "13",
  "categories": [1]
}

###

# Delete the post by id
DELETE {{host}}/{{prefix}}/{{parentPath}}/3 HTTP/1.1

###

# Get post by id
GET {{host}}/{{prefix}}/{{parentPath}}/1 HTTP/1.1

###

# Get all posts
GET {{host}}/{{prefix}}/{{parentPath}} HTTP/1.1

###
# Get all posts and filtres
GET {{host}}/{{prefix}}/{{parentPath}}?sortDirection=asc&categories=1&limit=1&page=1 HTTP/1.1

###


PATCH {{host}}/{{prefix}}/{{parentPath}}/1 HTTP/1.1
Content-Type:  {{contentType}}

{
  "title": "Новый заголовок"
}

###

